### PR TITLE
Dockerfile and extensive README instructions

### PR DESCRIPTION
**Pull request by murphye**
I was able to run PG-Strom in a container on a Linux host successfully. Please see the README for more details.

As noted in the README, I would consider this Docker image experimental, but it makes it easier to try PG-Strom, assuming the person has a Linux host with an NVIDIA card.

Note: This was tested on WSL 2 in Windows and it does not work because of the difference with the NVIDIA drivers in Windows. I did try to make this work without success. Definitely, a Linux host is needed.

Note: The scripts are directly from the PostGIS official Docker image.

### CODE REVIEW

**Comment by murphye** [comment]
So, to give you an idea of the performance of my test system using Docker (see the README.md), which has an NVIDIA Quadro RTX 3000 (6GB GDDR6).

I ran a query that runs the `st_contains` (check for points in polygons) on 3.5 million rows. Here are the results:

**Without GPU:** 4m 17s while consuming 2 CPU cores at 100%
**With GPU:** 4m 5s while consuming 1 CPU core at 100% and ~30% of GPU

Adding a GiST index for `geom` did not help, but to be expected since scanning all of the rows.

Can you think of any way to improve the GPU performance to achieve higher utilization possibly? Maybe this is a function of the non-exclusive use of GPU as I am also using the same GPU for my monitor.

**Comment by murphye** [comment]
I just updated the README.md showing an example with `st_contains` that has a 10x performance improvement due to PG-Strom. Great result!

**Comment by murphye** [comment]
I just noticed a new PG-Strom version is released. I will work on updating the Dockerfile to 15 soon.

**Comment by ma853529615** [comment]
Hi, @murphye. Thank you for this wonderful contribution. Have you tried deploying GPU direct feature of pg-strom in Docker.

**Pull request closed without merging**
